services:
  nginx:
    image: dhi.io/nginx:${NGINX_VERSION:?}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/snippets:/etc/nginx/snippets:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ${DATA_DIR:?}/letsencrypt/data:/etc/letsencrypt:ro
    ports:
      - "0.0.0.0:443:443"
      - "[::]:443:443"
    depends_on:
      - afonsodev-production-api
      - jrbaena-production-web
      - meteosaucana-production-web
      - psono
    restart: always

include:
  # Database
  - path: ./docker/compose/compose.database.yml
  # Application services
  - path: ./docker/compose/compose.afonsodev-production.yml
  - path: ./docker/compose/compose.jrbaena-production.yml
  - path: ./docker/compose/compose.meteosaucana-production.yml
  - path: ./docker/compose/compose.psono.yml
  # Extra tools
  - path: ./docker/compose/compose.alloy.yml
  - path: ./docker/compose/compose.certbot.yml
