services:
  nodepress-newsbot-test:
    image: ghcr.io/afonsodemori/nodepress-newsbot:test
    env_file:
      - .env
    depends_on:
      - nodepress-api-test
    networks:
      - infra_network
    restart: always
