services:
  ephemeral-web-test:
    image: ghcr.io/afonsodemori/ephemeral-web:${TAG_VERSION:-latest}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - infra_network
    restart: always
