server {
    server_name api.afonso.dev;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/afonso.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/afonso.dev/privkey.pem;

    location / {
        proxy_pass http://afonsodev-production-api:8080;
        include /etc/nginx/snippets/proxy.conf;
    }
}
