server {
    server_name jrbaena.com;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/jrbaena.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jrbaena.com/privkey.pem;

    location / {
        proxy_pass http://jrbaena-production-web:80;
        include /etc/nginx/snippets/proxy.conf;
    }
}
