server {
    server_name api.mipena.com;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/mipena.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mipena.com/privkey.pem;

    location / {
        proxy_pass http://mycrew-production-api:3000;
        include /etc/nginx/snippets/proxy.conf;
    }
}
