server {
    server_name vault.afonso.dev;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/afonso.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/afonso.dev/privkey.pem;

    # Project-specific security headers
    add_header Content-Security-Policy "default-src 'none'; manifest-src 'self'; connect-src 'self' https://static.psono.com https://api.pwnedpasswords.com https://storage.googleapis.com https://*.digitaloceanspaces.com https://*.blob.core.windows.net https://*.s3.amazonaws.com https://*.wasabisys.com; font-src 'self'; img-src 'self' https://favicon.psono.com data:; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'self'; child-src 'self'" always;

    location / {
        proxy_pass http://psono:80;
        include /etc/nginx/snippets/proxy.conf;
    }
}
