server {
    server_name status.afonso.dev;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/afonso.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/afonso.dev/privkey.pem;

    location / {
        proxy_pass http://uptime-kuma:3001;
        include /etc/nginx/snippets/proxy.conf;
    }
}

server {
    server_name status.mipena.com;

    include /etc/nginx/snippets/ssl-common.conf;

    ssl_certificate /etc/letsencrypt/live/mipena.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mipena.com/privkey.pem;

    location / {
        proxy_pass http://uptime-kuma:3001;
        include /etc/nginx/snippets/proxy.conf;
    }
}
