server {
  server_name vpn.labs.afonso.dev;

  include /etc/nginx/snippets/ssl-common.conf;

  ssl_certificate /etc/letsencrypt/live/afonso.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/afonso.dev/privkey.pem;

  # wg-easy bundles assets; a modest body size is plenty
  client_max_body_size 10M;

  location / {
    proxy_pass http://vpn:51821;
    include /etc/nginx/snippets/proxy.conf;
  }
}
