services:
  nodepress-web-production:
    image: ghcr.io/afonsodemori/nodepress-web:${WEB_TAG:-latest}
    env_file:
      - .env
    depends_on:
      - nodepress-api-production
    networks:
      - infra_network
    restart: always
