services:
  nodepress-api-production:
    image: ghcr.io/afonsodemori/nodepress-api:${API_TAG:?}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - infra_network
    restart: always
