services:
  nodepress-api-test:
    image: ghcr.io/afonsodemori/nodepress-api:${API_TAG:-test}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - infra_network
    restart: always
