services:
  postgres:
    image: dhi.io/postgres:${DATABASE_POSTGRES_VERSION:?}
    environment:
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD:?}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:
