services:
  nodepress-web-test:
    image: ghcr.io/afonsodemori/nodepress-web:${WEB_TAG:-test}
    env_file:
      - .env
    depends_on:
      - nodepress-api-test
    networks:
      - infra_network
    restart: always
